---
job: extension
config:
  # this name will be the folder and filename name
  name: "my_first_flux_lora_v1"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "/workspace/LoRas"
      # uncomment to see performance stats in the terminal every N steps
#      performance_log_every: 1000
      device: cuda:0
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      trigger_word: "YourCustomTriggerWord"
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16 # precision to save
        save_every: 100 # save every this many steps
        max_step_saves_to_keep: 20 # how many intermittent saves to keep
        push_to_hub: false #change this to True to push your trained model to Hugging Face.
        # You can either set up a HF_TOKEN env variable or you'll be prompted to log-in         
#       hf_repo_id: your-username/your-model-slug
#       hf_private: true #whether the repo is private or public
      datasets:
        # datasets are a folder of images. captions need to be txt files with the same name as the image
        # for instance image2.jpg and image2.txt. Only jpg, jpeg, and png are supported currently
        # images will automatically be resized and bucketed into the resolution specified
        # on windows, escape back slashes with another backslash so
        # "C:\\path\\to\\images\\folder"
        - folder_path: "/workspace/training_set"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 768, 1024 ]  # flux enjoys multiple resolutions
      train:
        batch_size: 1
        steps: 2000  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # probably won't work with flux
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 1e-4
        # uncomment this to skip the pre training sample
#        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for flux, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: true  # run 8bit mixed precision
#        low_vram: true  # uncomment this if the GPU is connected to your monitors. It will use less vram to quantize, but is slower.
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 100 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
          - "A photo of [trigger]"
          - "A photo of [trigger] resting on a table in a bustling coffee shop, the soft glow of the morning sun filtering through the window."
          - "A landscape painting of a serene park at sunset, with [trigger] nestled among the fallen autumn leaves, bathed in the warm golden light."
          - "An art studio filled with paintbrushes, easels, and a charcoal sketch of [trigger] prominently displayed, under the stark white light of a single bulb."
          - "A vintage mirror reflection of [trigger] in a boutique, surrounded by antique trinkets, captured as a sepia-toned image under soft, diffused lighting."
          - "A black and white photograph of a dimly lit jazz club with [trigger] subtly illuminated under the spotlight."
          - "A watercolor painting of a beach at dawn, the sand imprinted with seashells and [trigger], under the soft pastel hues of the morning light."
          - "A pencil drawing of [trigger] on a desk in a quiet library, surrounded by towering bookshelves, lit by the focused beam of a desk lamp."
          - "A vibrant digital art piece of a garden in full bloom, with [trigger] hidden amongst the flora, under the bright, midday sun."
          - "A Polaroid photo of [trigger] perched on a window sill of a high-rise apartment, the city's night lights twinkling in the background, bathed in the cool, ambient city light."
          - "A cozy kitchen filled with the aroma of fresh baking, [trigger] resting on the countertop, captured as a still life oil painting, under the warm, inviting glow of the kitchen lights."
        
        neg: ""  # not used on flux
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[name]"
  version: '1.0'
