name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d%m%Y')" >> $GITHUB_OUTPUT

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: ./comfy
          push: true
          tags: |
            keyvez/comfy:latest
            keyvez/comfy:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=keyvez/comfy:buildcache
          cache-to: type=registry,ref=keyvez/comfy:buildcache,mode=max

      - name: Build and push flux image
        uses: docker/build-push-action@v5
        with:
          context: ./comfy_flux
          push: true
          tags: |
            keyvez/comfy:flux
            keyvez/comfy:flux-${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=keyvez/comfy:buildcache
          cache-to: type=registry,ref=keyvez/comfy:buildcache,mode=max
